blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

dom_meditation/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

from dom_meditation import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", views.index, name='index'),
    path('admin/', admin.site.urls),
    path("products/", views.products, name='products'),
    path("club/", views.club, name='club'),
    path("practicums/", views.practicums, name='practicums'),
    path("meditations/", views.meditations, name='meditations'),
    path('blog/', include('blog.urls', namespace='blog')),
    path("efiry/", views.efiry, name='efiry'),
    path("oferta/", views.oferta, name='oferta'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) if settings.DEBUG else []

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Forum&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="icon" href="{% static 'images/core-img/logo-1.ico' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>


    <style>
        body {
            font-family: 'Montserrat', sans-serif;
            font-weight: 500;
        }

        a {
            text-decoration: None;
        }
    </style>

</head>
<body>


<nav class="navbar navbar-light fixed-top d-block d-lg-none">
  <div class="container-fluid">
      <a class="navbar-brand" href="#"></a>
    <button style="width: 70px; height: 70px; background-color: rgba(117,145,113,0.62)" class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Меню</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="margin-top: 20px" href="{% url 'products' %}">Товары</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" style="margin-top: 20px" href="{% url 'club' %}">Клуб ежедневной медитации</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style="margin-top: 20px" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Медитации и практикумы
            </a>
            <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
              <li><a class="dropdown-item" href="{% url 'practicums' %}">Практикумы</a></li>
              <li><a class="dropdown-item" href="{% url 'meditations' %}">Исцеляющие медитации</a></li>
              <li><a class="dropdown-item" href="#">Терапевтические эфиры</a></li>
            </ul>
          </li>
            <li class="nav-item">
            <a class="nav-link" style="margin-top: 20px" href="{% url 'blog:post_list' %}">Блог</a>
          </li>
        </ul>

      </div>
    </div>
  </div>
</nav>


<!-- NavBar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light d-none d-xl-block" style="">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.png' %}" width="60px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Товары</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'club' %}">Клуб ежедневной медитации</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Медитации и практикумы
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        <li><a class="dropdown-item" href="{% url 'practicums' %}">Практикумы</a></li>
                        <li><a class="dropdown-item" href="{% url 'meditations' %}">Исцеляющие медитации</a></li>
                        <li><a class="dropdown-item" href="{% url 'efiry' %}">Терапевтические эфиры</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Блог</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- NavBar -->

<h1>{% block header %}{% endblock header %}</h1>
<div>{% block content %}{% endblock content %}</div>



<!-- Footer -->


<footer class="text-center text-lg-start bg-body-tertiary text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Присоединяйтесь к Дому медитаций в социальных сетях</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
                <img src="{% static 'images/telegram_icon.png' %}" width="20px">
            </a>
            <a href="" class="me-4 text-reset">
                <img src="{% static 'images/youtube_icon.png' %}" width="40px">
            </a>
            <a href="" class="me-4 text-reset">
                <img src="{% static 'images/vk_icon.png' %}" width="25px">
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>Дом медитаций
                    </h6>
                    <p>
                        Присоединяйтесь к <a href="https://t.me/dommeditacii">Дому медитаций</a>  в телеграме
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Навигация
                    </h6>
                    <p>
                        <a href="/" class="text-reset">Главная</a>
                    </p>
                    <p>
                        <a href="{% url 'products' %}" class="text-reset">Товары</a>
                    </p>
                    <p>
                        <a href="{% url 'club' %}" class="text-reset">Клуб ежедневной медитации</a>
                    </p>
                    <p>
                        <a href="{% url 'blog:post_list' %}" class="text-reset">Блог</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Медитации и практикумы
                    </h6>
                    <p>
                        <a href="{% url 'practicums' %}" class="text-reset">Практикумы</a>
                    </p>
                    <p>
                        <a href="{% url 'meditations' %}" class="text-reset">Исцеляющие медитации</a>
                    </p>
                    <p>
                        <a href="{% url 'efiry' %}" class="text-reset">Терапевтические эфиры</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-5 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Контакты</h6>
                    <p><img src="{% static 'images/person_icon.png' %}" width="30px"></i>ИП Сечкина Наталья Ивановна</p>
                    <p>
                        <p>ИНН - 772015545999</p>
                    <p>ОГРНИП - 313774635100431</p>
                    </p>
                    <p>
                        <img src="{% static 'images/email.png' %}" width="28px">
                        natali@dommeditatcii.ru
                    </p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
        <p>Если у вас возникли какие-то проблемы или появились вопросы, обращайтесь в нашу <strong>службу заботы</strong> -
         <a href="mailto:natali@dommeditatcii.ru?subject=%D0%92%D0%BE%D0%BF%D1%80%D0%BE%D1%81%20%D0%B4%D0%BB%D1%8F%20%D1%81%D0%BB%D1%83%D0%B6%D0%B1%D1%8B%20%D0%B7%D0%B0%D0%B1%D0%BE%D1%82%D1%8B&body=%D0%97%D0%B4%D1%80%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D1%83%D0%B9%D1%82%D0%B5!%20%D0%A3%20%D0%BC%D0%B5%D0%BD%D1%8F%20%D0%B2%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B0%20%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0...">
             Написать письмо</a></p>
    </div>


    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
         <a style="color: black" href="{% url 'oferta' %}">Договор-оферта</a>
    </div>
    <!-- Copyright -->


    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2024 Все права защищены
    </div>

    <!-- Copyright -->
</footer>
<!-- Footer -->




</body>
</html>

templates/oferta.html
{% extends "base.html" %}
{% block head %}
{% load static %}

<meta http-equiv="refresh" content="0;url=https://api.unisender.com/ru/api/subscribe?format=json&api_key=6jtuanh76kp18ms67tb74d658nb3xx5pt1rccmka&list_ids=985&fields[email]=
tigeeva100@mail.ru&fields[Name]=Ivan+Ivanov&double_optin=3&tags=RusMag" />

{% endblock head %}

{% block content %}

<div style="margin-top: 40px;" class="container">
  <div class="row">
    <div class="col-12">
      <h3>Оферта</h3>
    </div>
    <div class="row">
      <div class="col-12">
        <p style="white-space:pre-line;">
          <strong>Индивидуальный предприниматель Сечкина Наталья Ивановна</strong>, зарегистрированная в реестре индивидуальных предпринимателей под № 313774635100431 (далее - «Администрация»), размещает настоящую публичную оферту в соответствии со ст. 435 и 4357 Гражданского Кодекса Российской Федерации (далее - «Оферта») с предложением физическим и (или) юридическим лицам, действующим в лице представителя, заключить Договор на нижеследующих условиях:

<strong>1. Термины</strong>

1.1. В целях единого толкования и понимания, нижеприведенные термины используются в следующем значении:

1.1.1. Акцепт публичной оферты - полное и безоговорочное принятие Пользователем условий настоящей публичной
Оферты (далее - «Акцепт»).

1.1.2. Договор - возмездное соглашение между Администрацией и Пользователем, заключенное посредством Акцепта
публичной Оферты (далее - «Договор» или «Оферта», в зависимости от контекста).

1.1.3. Пользователь - физическое лицо, заключившее с Администрацией Договор на условиях, содержащихся в настоящей
публичной Оферте (далее - «Пользователь»).

1.1.4. Сервис - веб-сайт, расположенный в сети интернет по адресу https://natalisechkina.ru (далее - «Сервис»).

<strong>2. Предмет договора и общие положения</strong>

2.1. В соответствии с настоящим Договором-Офертой Администрация обязуется оказать Пользователю информационные услуги.
2.2. Стороны не вправе ссылаться на незаключенность настоящего Договора при встречном предоставлении в порядке статьи 432 ГКРФ.

2.3. Новая редакция Договора (Оферты) вступает в силу в день ее опубликования.

<strong>3. Акцепт оферты</strong>

З.1 Акцептом Договора-Оферты является факт оплаты Пользователем Договора; конклюдентные действия Пользователя или любое взаимодействие Пользователя с функционалом Сервиса в любом объеме‚ иное волеизъявление, исходя существа правоотношений Сторон.
3.2. До Акцепта настоящей оферты Пользователь обязуется ознакомиться с ее содержанием. При наличии каких-либо сомнений в толковании условий настоящей Оферты Пользователь вправе до совершения Акцепта обратиться к Администрации с письменным запросом, в том числе посредством сети интернет, иным способом, исходя из существа правоотношений, в ином случае Пользователь не имеет права ссылаться на незнание Оферты, если иное не установлено императивными нормами законодательства РФ.
3.3. Администрация вправе по своему усмотрению создавать, изменять или отменять условия настоящей Оферты, если иное не предусмотрено императивными нормами законодательства РФ.
3.4. Совершая Акцепт, Пользователь подтверждает свою полную дееспособность. Акцепт не может считаться совершенным в случае, если совершен недееспособным Лицом, а также лицом, не достигшим возраста 18 лет (исключая случай эмансипации). Риск совершения Акцепта недееспособным лицом или лицом, не достигшим совершеннолетия, лежит на законных представителях такого лица.
3.5. Администрация сообщает, что данная Оферта действует совместно с Согласием на получение рекламы, принимая условия настоящей Оферты, Пользователь также ознакомился с условиями Согласия на получение рекламы и безоговорочно принимает их в полном объеме.

3.6. В случае если Согласие на получение рекламы противоречит Оферте, приоритет следует отдавать условиям Оферты.

З.7. Оплата Договора Пользователем производится посредством ООО "РОБОКАССА" в соответствии с информацией, представленной на соответствующих страницах (разделах) Сервиса Администрации. Пользователь Акцептом настоящей Оферты подтверждает также, что ознакомился с офертой, политикой конфиденциальности и иными документами сервиса приема платежей (платежной системы).

<strong>4. Финансовые условия</strong>

4.1 Стоимость каждого обязательства, исполняемого в соответствии с настоящей офертой, определяется Администрацией в одностороннем порядке и сообщается Пользователю посредством Сервиса.
4.2. Информация сообщается до Акцепта Оферты, Акцепт не может считаться совершенным без предоставления необходимой информации, а Договор не может считаться заключенным.

4.3. Администрация вправе в одностороннем порядке изменять стоимость указанных обязательств, если такое изменение стоимости не нарушит императивных норм ГК РФ.
4.4. Моментом исполнения обязательства Пользователя по уплате денежных средств в пользу Администрации считается момент поступления денежных средств на расчетный счет Администрации.

<strong>5. Срок действия договора</strong>

5.1 Настоящий Договор вступает в силу с даты его Акцепта и заключен на неопределенный срок.

5.2. Расторжение (прекращение действия) настоящего Договора означает, в том числе, прекращение действия всех приложений, дополнительных соглашений и иных документов к нему, если иное не предусмотрено в соответствующих приложениях и дополнительных соглашениях (иных документах) к Договору.

<strong>6. Ответственность сторон</strong>

6.1. Стороны несут ответственность за последствия собственных действий в соответствии с действующим законодательством Российской Федерации.

6.2. Вся информация предоставляется в исходном виде, без гарантий полноты или своевременности, без иных, явно выраженных или подразумеваемых гарантий. Доступ к Сервису, а также использование его содержимого осуществляются исключительно по усмотрению и под ответственность Пользователя.

6.3. Пользователь осознает, что все материалы Сервиса или любая их часть могут сопровождаться рекламой. Пользователь согласен с тем, что Администрация не несет какой-либо ответственности и не имеет каких-либо обязательств в связи с такой рекламой.

6.4. Пользователь заверяет Администрацию о достоверности предоставляемой информации.

6.5. Пользователь обязуется не использовать программное обеспечение (и иной код) для автоматизированного сбора информации и (или) взаимодействия с Сервисом, в ином случае Пользователь обязан возместить Администрации убытки, причиненные указанными действиями, в полном объеме.
6.6. Пользователь при взаимодействии с Администрацией обязуется не распространять информацию, которая направлена на пропаганду войны, разжигание национальной, расовой или религиозной ненависти и вражды, а также иной информации, за распространение которой предусмотрена уголовная или административная ответственность.

<strong>7. Разрешение споров</strong>

7.1. Все споры и разногласия, которые могут возникнуть между сторонами по настоящему Договору, будут разрешаться в соответствии с законодательством Российской Федерации.

<strong>8. Заключительные положения</strong>

8.1. В случае признания недействительным какого-либо положения настоящего Договора, остальные его положения не утрачивают свою силу.

8.2. Если иное прямо не предусмотрено Договором, ничто в Договоре не может пониматься как установление между Сторонами агентских отношений, отношений товарищества, отношений по совместной деятельности, отношений личного найма, либо каких-то иных отношений, прямо не предусмотренных Договором.

8.3. Обо всех изменениях своего местонахождения или банковских реквизитов, а равно других обстоятельств, имеющих значение для надлежащего исполнения настоящего Договора, Стороны обязаны извещать друг друга незамедлительно.

8.4. В случае изменения каких-либо сведений о Стороне в период действия настоящего Договора, такая Сторона обязуется уведомить об этом другую Сторону в течение 5 календарных дней, в противном случае, все связанные с отсутствием такого уведомления риски Сторона несет самостоятельно.

8.5. Принимая настоящую Оферту, Стороны подтверждают, что:

8.5.1. ознакомились с Договором и им понятны значения используемых в Договоре терминов, слов и выражений согласно их нормативно-правовому определению или толкованию, указанному в Договоре;

8.5.2. заключают Договор добровольно и согласны с его условиями;

8.5.5. имеют право на самостоятельное совершение сделки (в частности, заключение Договора) и действий, предусмотренных Договором.

<strong>9. Реквизиты администрации</strong>

ИП Сечкина Наталья Ивановна
Адрес регистрации: 101000, г Москва
ОГРНИП 313774635100431‚ ИНН 772015545999
Банк АО "ТБанк"
БИК 044525974


        </p>
      </div>
    </div>
  </div>
</div>



{% endblock content %}